# Generated by Django 3.1.6 on 2021-02-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='achievement_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='distance_in_feet',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
