# Generated by Django 3.1.6 on 2021-02-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_auto_20210218_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='distance_in_feet',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
