# Generated by Django 3.1.6 on 2021-02-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0005_drone_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='gender',
            field=models.CharField(choices=[('M', 'Female'), ('F', 'Male')], default='M', max_length=100),
        ),
    ]
